### ISSUE TITLE
Crear guía de contribución

### ISSUE THREAD

**Issue by jroji** [proyectosolidus/ProyectoSolidus#1]
Como posible contribuidor, necesito una guía accesible que me indique:
- Cómo unirme a un proyecto/equipo
- Que requisitos debo cumplir para colaborar
- Quién puede resolver mis dudas
- Que implica colaborar en este proyecto

**Comment by pabrodez** [comment]
Hola! Es la primera vez que contribuyo en un Issue de GitHub y también la primera que intento redactar una guía de contribución, pero aquí va una primera pincelada. Puede que sea una buena idea diseñar una plantilla para abrir Issues y Pull Requests, también una sección en el Código de Conducta o en la Guía de Contribución sobre el contenido del mensaje del commit (asumiendo que el número de contribuyentes vaya a ser grande).


# Guía de contribución

## ¿Cómo puedo unirme?
Si deseas colaborar puedes inscribirte en el [formulario](https://docs.google.com/forms/d/e/1FAIpQLSdvnnTbpeFz1PTkVl5vDIrfWjP-TeDhZGFzpy5aB-d0OzZk5g/viewform). Unos de los administrados se pondrá en contacto contigo y te invitará al Slack.

## Que implica colaborar en este proyecto
Si deseas colaborar debes, ante todo, seguir el Código de conducta. Ayúdanos a hacer del Proyecto Solidus una comunidad abierta e inclusiva. Por favor, lee y sigue el [Código de Conducta](https://github.com/proyectosolidus/ProyectoSolidus/blob/main/CODE_OF_CONDUCT.md).

## Para empezar
1. Crea un [fork](https://docs.github.com/es/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) de este repositorio
2. Clona tu fork
`$ git clone SSH/HTTPS`
`$ cd proyectosolidus`
3.  Haz cambios en una nueva rama `$ git checkout -b nueva-rama master`

## Si encuentras un problema
Puedes crear un Issue en el repositorio o un Pull Request con el problema solucionado.

## Creando un Pull Request
- Haz cambios o añade el contenido a la rama que has creado anteriormente
- Haz commit con los cambios `$ git commit -a` Asegúrate de que el mensaje es descriptivo y sigue el Código de Conducta.
- Haz push con la rama a Github `git push origin nueva-rama`
- En GitHub, haz un Pull Request en `main`

## Dudas o preguntas
Puedes poner en contacto con los administradores de la comunidad:
- José Manuel Lucas / @jmlweb / josemanuel@jmlweb.es
- Jon Rojí / @jroji

También puedes enviar un mensaje en alguno de los canales de Slack.

**Comment by jroji** [comment]
Hola @pabrodez ! gracias por comentar!
Te parece hacer una rama con esto en un md, y abrir PR al repositorio?

así la vinculamos también a esta issue, y vamos comentando en la PR 😃

**Comment by jmlweb** [comment]
@pabrodez Si tienes cualquier duda sobre el proceso, ¡cuenta con mi hacha!
