### ISSUE TITLE
Crear código de conducta

### ISSUE THREAD

**Issue by jroji** [proyectosolidus/ProyectoSolidus#2]
Como posible colaborador, quiero acceder a un documento que especifique el código de conducta dentro de la comunidad. Enlaces interesantes a tener en cuenta en la sección enlaces-interes de slack

**Comment by jmlweb** [comment]
Si alguna persona tiene alguna sugerencia, sea bienvenida 😄

**Comment by jroji** [comment]
Lo ideal es crear la PR asignando a esta issue para tener control de "que se ha cambiado"

**Comment by jroji** [comment]
Cerramos y si hay que modificar se abre otra
