### ISSUE TITLE
Crear README

### ISSUE THREAD

**Issue by jroji** [proyectosolidus/ProyectoSolidus#3]
Como posible colaborador, quiero acceder a un documento que especifique:
- Qué es Proyecto Solidus
- Cual es el objetivo
- Posibles formas de colaborar
- Guía de enlaces de interés
- Herramientas y requisitos

**Comment by pabrodez** [comment]
Si te parece bien, voy a abrir un PR con README básico para ir tirando. No he desarrollado el apartado de requisitos y herramientas porque creo que es algo que los administradores pueden ayudar a detallar.
