### ISSUE TITLE
Escoger licencia para repositorio y proyectos

### ISSUE THREAD

**Issue by jroji** [proyectosolidus/ProyectoSolidus#8]
Escoger una licencia para controlar contribuciones y acreditaciones del proyecto

**Comment by pabrodez** [comment]
Tenemos que elegir, como mínimo, quién/es van a ostentar el Copyright (a menos que optemos por una licencia sin condiciones). GitHub tiene una lista de licencias para facilitar la comparación https://choosealicense.com/licenses/

**Comment by jroji** [comment]
Yo quizás arrancaría con una GNU GPLv3. Más adelante se puede valorar en cada proyecto de cara a las atribuciones o las condiciones de cada uno. Os parece que de momento metamos esta y sigamos viendo en esta issue si hay alguna duda o cambio que se quiera realizar?
